stages:
#- test
- build
- deploy

variables:
  S3_BUCKET: themis-desk.iviplay.io

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/


build_android:
  stage: build
  image: node:18.17  #agileek/ionic-framework
  only:
    - dev
    - preprod
    - prod
  script:
    # - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    # - source ~/.bashrc
    # - nvm  install v14.20.0
    # - nvm use v14.20.0
    #- npm install --legacy-peer-deps
    - npm -v
    - npm install  
    - npm install -g @ionic/cli
    - npm install -g @angular/cli
    - rm -rf android 
    - ionic build
    - ls -l www
  artifacts:
    paths:
      - www
    expire_in: 1 hour

deploy-dev:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    # name: banst/awscli
    # entrypoint: [""]
  dependencies:
    - build_android
  script:
    - export ACCESS_ID=${ACCESS_ID}
    - export ACCESS_SECRET=${ACCESS_SECRET}
    - aws configure set aws_access_key_id ${ACCESS_ID}
    - aws configure set aws_secret_access_key ${ACCESS_SECRET}
    - aws configure set default.region eu-west-3
    - cd www && aws s3  sync . s3://themis-desk.iviplay.io 
  only:
    - dev

deploy-preprod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    # name: banst/awscli
    # entrypoint: [""]
  dependencies:
    - build_android
  script:
    - export AWS_ACCESS_KEY_ID=${ACCESS_ID}
    - export AWS_SECRET_ACCESS_KEY=${ACCESS_SECRET}
    #- unset $ACCESS_ID
    #- unset $ACCESS_SECRET
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set default.region eu-west-3
    - aws s3 rm s3://dev-themis-desk.iviplay.io --recursive
    - cd www && aws s3  sync . s3://dev-themis-desk.iviplay.io/

  only:
    - preprod
#
deploy-prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    # name: banst/awscli
    # entrypoint: [""]
  dependencies:
    - build_android
  script:
    - export ACCESS_ID=${ACCESS_ID}
    - export ACCESS_SECRET=${ACCESS_SECRET}
    - aws configure set aws_access_key_id ${ACCESS_ID}
    - aws configure set aws_secret_access_key ${ACCESS_SECRET}
    - aws configure set default.region eu-west-3
    - cd www && aws s3  sync . s3://prod-bienvenue-desk.iviplay.io --delete
  only:
    - prod
  when: on_success