export  default {
  color: "ivi-green",
  colorHtml: "var(--ion-green)",
  colorSearch: "var(--ion-grey)",
  colorInput: "input-green",//"#e7f5e2",
  bg: "ivi-bg-green",
  title: "ivi-title-green",
  titleList: "ivi-title-list-green",
  background: "ivi-bg-image-green",
  backgroundImage: "ivi-bg-image-green",
  hover: "ivi-hover-green",
  input: "ivi-input-green",
  searchbar: "ivi-searchbar-green",
  scrollbar: 'scrollbar-green',
  menubg: 'menu-bg-green',
  welcomeText: 'ivi-welcome-text-green',
  subMenuBg: 'sub-menu-bg-green',
  family: 'roboto',
  colorPassive: 'pmu-color-passive',
  colorActive: 'pmu-color-active',
  colorWhite: 'color-white-icon',
  colorServiceCard: 'service-green',
  bgButton: 'bg-white-green',
  borderItem: 'border-green',
}
