export  default {
  color: "ivi-red",
  colorHtml: "var(--ion-red)",
  colorInput: "input-red",//"#f5e7e2",
  colorSearch: "var(--ion-grey)",
  bg: "ivi-bg-red",
  title: "ivi-title-red",
  titleList: "ivi-title-list-red",
  background: "ivi-bg-image-red",
  backgroundImage: "ivi-bg-image-red",
  hover: "ivi-hover-red",
  input: "ivi-input-red",
  searchbar:"ivi-searchbar-red",
  scrollbar: 'scrollbar-red',
  menubg: 'menu-bg-red',
  welcomeText: 'ivi-welcome-text-red',
  family: 'century',
  colorPassive: 'sci-color-passive',
  colorActive: 'sci-color-active',
  colorWhite: 'color-white-icon',
  bgButton: 'bg-btn-red',
  colorServiceCard: 'service-red',
  borderItem: 'border-red',
}
